[project]
name = "Sdlp"
dynamic = ["version"]

description = "A simple video downloader based on yt-dlp"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]

authors = [{ name = "writedev" }]
classifiers = [
    "Topic :: Multimedia :: Video :: Capture",
    "Topic :: Multimedia :: Video",
    "Topic :: Multimedia :: Sound/Audio :: Capture/Recording",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

requires-python = ">=3.13"
dependencies = [
    "curl-cffi>=0.14.0",
    "ffmpeg>=1.4",
    "rich>=14.3.2",
    "typer>=0.21.1",
    "yt-dlp>=2026.2.4",
]


[project.scripts]
sdlp = "sdlp.cli:app"

[tool.setuptools.packages.find]
include = ["sdlp*"]

[tool.setuptools.dynamic]
version = { attr = "sdlp.__version__" }

[project.urls]
repository = "https://github.com/writedev/Sdlp"

[tool.ty.analysis]
respect-type-ignore-comments = false

[tool.ruff]
line-length = 88
target-version = "py311"

exclude = [".git", ".venv", "build", "dist", "__pycache__"]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort (imports)
    "B",   # flake8-bugbear
    "UP",  # pyupgrade
    "C4",  # flake8-comprehensions
    "SIM", # simplifications
]

ignore = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["my_project"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
